colleen:
	- sh test_colleen.sh

grace:
	- sh test_grace.sh

all: colleen grace

clean:
	rm rb_colleen_test
	rm py_colleen_test
	rm Grace_kid.py
	rm Grace_kid.rb

fclean: clean

re: fclean all

.PHONY: all clean fclean re